# See overlays: compose.demo.yaml for the demo, compose.override.yaml for dev, compose.prod.yaml for prod.


secrets:
  postgres_root_username:
#   file: ../private/postgres_root_username
    environment: POSTGRES_ROOT_USERNAME
  postgres_root_password:
#    file: ../private/postgres_root_password
    environment: POSTGRES_ROOT_PASSWORD
services:

  vialo-api:
    stop_grace_period: 30s
    build:
      context: ./
      dockerfile: ./vialo-api/Dockerfile
    restart: unless-stopped
    volumes:
      - ../vialo.toml:/app/vialo.toml
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - "../.env"
    environment:
      # Override .env host
      DATABASE_URL: postgresql://${POSTGRES_ROOT_USERNAME}:${POSTGRES_ROOT_PASSWORD}@postgres:5432/vialo?schema=public
  postgres:
    build: ./postgres
    volumes:
      - "../data/postgres:/var/lib/postgresql"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'pg_isready -U "$(cat /run/secrets/postgres_root_username)" -d vialo',
        ]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_root_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_root_username
      - POSTGRES_DB=vialo
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin

    secrets:
      - postgres_root_password
      - postgres_root_username
  #     - postgres_db_password
  #     - postgres_db_username
