--
-- Bulletin board
--
CREATE TYPE post_visibility AS ENUM('public', 'logged_in', 'board');

CREATE TABLE boards (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  label int NOT NULL REFERENCES i18n_index (id),
  slug citext UNIQUE NOT NULL,
  icon citext,
  group_id uuid REFERENCES account_groups (id) ON DELETE CASCADE, -- Linked group id (optional)
  default_post_visibility post_visibility NOT NULL default 'board',
  system bool NOT NULL DEFAULT false
);

INSERT INTO
  boards (id, label, slug, default_post_visibility, system)
VALUES
  (
    0,
    (
      SELECT
        insert_i18n_strings (ARRAY['en', 'de'], ARRAY['Home', 'Hauptseite'])
    ),
    'home',
    'board',
    'true'
  );

CREATE TYPE board_perm AS ENUM('view', 'post', 'moderate', 'admin');

CREATE TABLE board_group_perms (
  id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  group_id uuid REFERENCES account_groups (id) ON DELETE CASCADE,
  board_id int NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
  perm board_perm NOT NULL,
  UNIQUE NULLS NOT DISTINCT (group_id, board_id)
);

CREATE TABLE board_posts (
  id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  account_id uuid REFERENCES accounts_people (id) ON DELETE CASCADE, -- TODO: Maybe app should handle transfering some posts to others or implement posts owned by groups
  board_id int NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
  icon text,
  title int REFERENCES i18n_index (id),
  content int REFERENCES i18n_index (id),
  content_html int REFERENCES i18n_index (id),
  content_plain int REFERENCES i18n_index (id),
  location int REFERENCES i18n_index (id),
  event_from timestamptz,
  event_to timestamptz,
  created_at timestamptz NOT NULL default NOW(),
  visibility post_visibility not null default 'board'
);

CREATE INDEX board_posts_event_idx ON board_posts (event_from, event_to);

CREATE INDEX board_posts_created_at_idx ON board_posts (created_at);

CREATE INDEX board_posts_board_id_idx ON board_posts (board_id);

CREATE INDEX board_posts_account_id_idx ON board_posts (account_id);

-- This code remains here as a memorial to a stupid idea
--
-- CREATE TABLE board_includes (
--     source_board int REFERENCES boards (id) ON DELETE CASCADE,
--     dest_board int REFERENCES boards (id) ON DELETE CASCADE,
--     PRIMARY KEY (dest_board, source_board)
-- );
CREATE TABLE board_pinned_posts (
  post_id int NOT NULL REFERENCES board_posts (id) ON DELETE CASCADE,
  board_id int NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
  pin_priority int NOT NULL DEFAULT 0,
  pinned_until timestamptz,
  PRIMARY KEY (post_id, board_id)
);

-- "posts pinned to this board" lookups
CREATE INDEX board_pinned_posts_board_id_idx ON board_pinned_posts (board_id, post_id) INCLUDE (pinned_until);

CREATE TABLE board_subscriptions (
  id uuid PRIMARY KEY default gen_random_uuid(),
  account_id uuid REFERENCES accounts_people (id) ON DELETE CASCADE,
  board_id int NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
  UNIQUE (account_id, board_id)
);

-- board_id-first subscriber lookups (for post notifications)
CREATE INDEX board_subscriptions_board_id_idx ON board_subscriptions (board_id);

CREATE FUNCTION account_board_perm_exists (acid uuid, bid int, min_perm board_perm) RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT (
        (acid IS NOT NULL AND account_role_exists(acid, 'board_manager'))
        OR EXISTS (
            SELECT 1 FROM board_group_perms
            WHERE board_id = bid
              AND group_id IS NULL
              AND perm >= min_perm
        )
        OR (acid IS NOT NULL AND EXISTS (
            SELECT 1 FROM account_group_memberships agm
            JOIN board_group_perms bgp ON agm.group_id = bgp.group_id
            WHERE bgp.board_id = bid
              AND agm.account_id = acid
              AND bgp.perm >= min_perm
        ))
    )
$$;
