[package]
name = "vialo-dhcp"
version = "0.1.0"
edition = "2024"

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = { enable = true }

[dependencies]
dora-core = { git = "https://github.com/bluecatengineering/dora.git", rev = "64f21e2ae7d28047f46d99355eebc935bda88e15" }
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "uuid", "ipnetwork", "mac_address", "migrate"] }
anyhow = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive", "env"] }
uuid = "1"
mac_address = "1"
rtnetlink = "0.21.0"
futures = "0.3.33"
