# Applies to builds of vialo-api/Dockerfile (context = workspace root).
# Allowlist: only the workspace manifests and member crates are build inputs.
*
!Cargo.toml
!Cargo.lock
!vialo-api
!vialo-common
!vialo-dhcp
# Non-build inputs inside the allowed directories
vialo-api/Cargo.lock
vialo-api/Dockerfile*
vialo-api/debian
vialo-common/Cargo.lock
vialo-dhcp/Dockerfile*
vialo-dhcp/debian
vialo-dhcp/compose.yaml
vialo-dhcp/test
**/target
**/.DS_Store
