# proxy = "socks5://127.0.0.1:1337"

[public]
cors_origins = ["http://localhost:3000", "http://localhost:3001"]
listen = "0.0.0.0:8000"

[hooks]
listen = "0.0.0.0:8011"

[email]
url = { unsubscribe = "https://xyz.example.com/unsub/", post =  "https://xyz.example.com/post/", board = "https://xyz.example.com/board/", preferences= "https://xyz.example.com/prefs/" }

[auth]
type = "kratos"
frontend_url = "http://localhost:4433"
admin_url = "http://localhost:4434"
