name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    # Applies to all 'run' steps in this job
    defaults:
      run:
        working-directory: ./vialo-api

    steps:
      - uses: actions/checkout@v6

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./vialo-api"
      # - name: Build
      #   run: cargo build --verbose

      # - name: Run tests
      #   run: cargo test --verbose

      - name: Generate OpenAPI spec
        run: cargo run --bin openapi-spec -- openapi.json

      - name: Upload OpenAPI Artifact
        uses: actions/upload-artifact@v7
        with:
          name: openapi-spec
          # Since this is an action, it ignores the default working directory above.
          # You must include the subfolder path explicitly.
          path: ./vialo-api/openapi.json
          if-no-files-found: error
  deploy-docs:
    # This ensures the deploy job only runs after the build job is successful
    needs: build

    # Required permissions for GitHub Pages deployments
    permissions:
      pages: write
      id-token: write

    # Links this job to the built-in GitHub Pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Download OpenAPI Artifact
        uses: actions/download-artifact@v8
        with:
          name: openapi-spec
          # Downloads the artifact into a new temporary folder
          path: ./pages-build

      - name: Generate index.html
        run: |
          cat << 'EOF' > ./pages-build/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <title>Vialo API</title>
              <meta charset="utf-8"/>
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>body { margin: 0; padding: 0; }</style>
            </head>
            <body>
              <redoc spec-url="openapi.json"></redoc>
              <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"></script>
            </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./pages-build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
